{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "kaos.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "kaos.labels" . | indent 4 }}
rules: []
{{- end -}}
