{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "kaos.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "kaos.labels" . | indent 4 }}
roleRef:
  kind: Role
  name: {{ template "kaos.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: {{ template "kaos.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end -}}
